CREATE DATABASE student360 OWNER s360_owner;
CREATE DATABASE student360_test OWNER s360_owner;
\c student360
CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE EXTENSION IF NOT EXISTS citext;
\c student360_test
CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE EXTENSION IF NOT EXISTS citext;
